Numpy helps us to deal with the array and matrix.

In [1]:
import numpy as np 
import pandas as pd

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [4]:
#if we use different datatypes inside the same list then it will type conversion all the data into upper datatypes.
np.array([1,2,3,4,5,"Nitesh",4.5,6+1j])   #It will convert all the data into string.

array(['1', '2', '3', '4', '5', 'Nitesh', '4.5', '(6+1j)'], dtype='<U64')

In [5]:
np.array([1,2,3,4,5,3.6,4.5]) #It will convert all the data into floating point.

array([1. , 2. , 3. , 4. , 5. , 3.6, 4.5])

In [6]:
#1D array
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [7]:
#2D array
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [8]:
#3D array
np.array([[[1,2],[5,6]],[[3,4],[4,5]]])

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [4, 5]]])

In [9]:
np.array([1,2,4],ndmin=3)  #It will convert the data into 3d array

array([[[1, 2, 4]]])

In [10]:
np.array([1,2,3],dtype=complex)  #we can convert the datainto any datatype.

array([1.+0.j, 2.+0.j, 3.+0.j])

In [11]:
np.array([1,2,3],dtype=str)

array(['1', '2', '3'], dtype='<U1')

In [12]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [13]:
arr=np.array([(2,3)],dtype=[("a","<i2"),("b","<i4")])

In [14]:
arr

array([(2, 3)], dtype=[('a', '<i2'), ('b', '<i4')])

In [15]:
arr[0][0]

2

In [16]:
type(arr[0][0])

numpy.int16

In [17]:
type(arr[0][1])  #we have the option of "<i2","<i4","<i8" which denote 16,32,64 bit respectively.

numpy.int32

In [18]:
l=[1,2,3,4,5,6,7,8,9,10]

In [19]:
np.array(l)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
np.asarray(l)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
np.asanyarray(l)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
mat=np.matrix(arr)
np.asanyarray(mat)

matrix([[(2, 3)]], dtype=[('a', '<i2'), ('b', '<i4')])

In [23]:
issubclass(np.matrix,np.ndarray)   #we can see that matix is the sub class of ndarray.

True

In [24]:
issubclass(np.ndarray,np.matrix)   #we can see that ndarray isnot the sub class of matix.

False

In [25]:
arr= [[3,4],[4,5]]

In [26]:
a=arr  #sallow copy--point to the same memory location. 

In [27]:
b=np.copy(a) #deep copy--create b into new memory loaction.

In [28]:
arr[0][0]=1

In [29]:
arr

[[1, 4], [4, 5]]

In [30]:
#here we can see that a is referring to the same memory location as arr, so the change of the value of the arr also change the value of a. 
a  

[[1, 4], [4, 5]]

In [31]:
#here we can see b is just copying the value of a and is in another memory location so change in arr doesnot chnage the value of b.
b

array([[3, 4],
       [4, 5]])

In [32]:
arr[0:2]  #indexing is also present in arr.

[[1, 4], [4, 5]]

In [33]:
np.fromfunction(lambda i,j:i==j,(4,4))  #4*4 matrix created in which we can check if the rows and columns is same.


array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [34]:
np.fromfunction(lambda i,j:i*j,(4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [35]:
np.fromfunction(lambda i,j:i**j,(4,4))

array([[ 1.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  2.,  4.,  8.],
       [ 1.,  3.,  9., 27.]])

In [36]:
gen= (i*i for i in range(5))

In [37]:
gen

<generator object <genexpr> at 0x000001FF08DBE200>

In [38]:
def test(x):
    yield(x)

In [39]:
test(5)

<generator object test at 0x000001FF08DBE4A0>

In [40]:
np.fromiter(gen,dtype=int)

array([ 0,  1,  4,  9, 16])

In [41]:
np.fromiter(range(5),dtype=int)

array([0, 1, 2, 3, 4])

In [42]:
#converting string into ndarray.
np.fromstring("1,2,3,4,5,6,7,8,9,10",sep=",",dtype=int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr=np.array([[1,2,3,4],[5,6,7,8],[4,5,6,7]])

In [44]:
arr.ndim

2

In [45]:
arr.size

12

In [46]:
arr.shape

(3, 4)

In [47]:
arr1=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [48]:
arr1.ndim

3

In [49]:
arr1.shape #that means we have 2 no. of 2*3 data. 

(2, 2, 3)

In [50]:
list(range(5))

[0, 1, 2, 3, 4]

In [51]:
list(range(6.6))  #range function only takes integer value.

TypeError: 'float' object cannot be interpreted as an integer

In [52]:
np.arange(6.6)

array([0., 1., 2., 3., 4., 5., 6.])

In [53]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [54]:
np.arange(5,9,0.5)  #range form 5 to 9 with a jump of 0.5.

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5])

In [55]:
np.arange(9,2,0.4)

array([], dtype=float64)

In [56]:
np.arange(9,2,-0.4)

array([9. , 8.6, 8.2, 7.8, 7.4, 7. , 6.6, 6.2, 5.8, 5.4, 5. , 4.6, 4.2,
       3.8, 3.4, 3. , 2.6, 2.2])

In [57]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [58]:
np.arange(1.5,5.5)

array([1.5, 2.5, 3.5, 4.5])

In [59]:
np.arange(1,5.5,0.6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. , 4.6, 5.2])

In [60]:
#it is generating a data in between two points into equal parts
#by default it will give 50 datas.
np.linspace(2,5)

array([2.        , 2.06122449, 2.12244898, 2.18367347, 2.24489796,
       2.30612245, 2.36734694, 2.42857143, 2.48979592, 2.55102041,
       2.6122449 , 2.67346939, 2.73469388, 2.79591837, 2.85714286,
       2.91836735, 2.97959184, 3.04081633, 3.10204082, 3.16326531,
       3.2244898 , 3.28571429, 3.34693878, 3.40816327, 3.46938776,
       3.53061224, 3.59183673, 3.65306122, 3.71428571, 3.7755102 ,
       3.83673469, 3.89795918, 3.95918367, 4.02040816, 4.08163265,
       4.14285714, 4.20408163, 4.26530612, 4.32653061, 4.3877551 ,
       4.44897959, 4.51020408, 4.57142857, 4.63265306, 4.69387755,
       4.75510204, 4.81632653, 4.87755102, 4.93877551, 5.        ])

In [61]:
#it is generating a data in between two points(2,5) into equal parts of 6 values.
np.linspace(2,5,6)

array([2. , 2.6, 3.2, 3.8, 4.4, 5. ])

In [62]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [63]:
np.zeros((2,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [64]:
np.zeros((2,5,4,1))

array([[[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]]])

In [65]:
np.ones(4)

array([1., 1., 1., 1.])

In [66]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [67]:
np.ones((2,3,1))

array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

In [68]:
np.ones((2,3,1))+5

array([[[6.],
        [6.],
        [6.]],

       [[6.],
        [6.],
        [6.]]])

In [69]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [70]:
np.empty((2,3))

array([[6., 6., 6.],
       [6., 6., 6.]])

In [71]:
np.eye(3) #identity matrixes

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [72]:
np.linspace(2,4,4)

array([2.        , 2.66666667, 3.33333333, 4.        ])

In [73]:
np.linspace(2,4,4,endpoint=False,axis=0)  #it will not include the last value which is 4.

array([2. , 2.5, 3. , 3.5])

In [74]:
np.linspace([2,1],3,endpoint=False,axis=1)

array([[2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
        2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
        2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
        2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
        2.88, 2.9 , 2.92, 2.94, 2.96, 2.98],
       [1.  , 1.04, 1.08, 1.12, 1.16, 1.2 , 1.24, 1.28, 1.32, 1.36, 1.4 ,
        1.44, 1.48, 1.52, 1.56, 1.6 , 1.64, 1.68, 1.72, 1.76, 1.8 , 1.84,
        1.88, 1.92, 1.96, 2.  , 2.04, 2.08, 2.12, 2.16, 2.2 , 2.24, 2.28,
        2.32, 2.36, 2.4 , 2.44, 2.48, 2.52, 2.56, 2.6 , 2.64, 2.68, 2.72,
        2.76, 2.8 , 2.84, 2.88, 2.92, 2.96]])

In [75]:
np.logspace(2,5,4) #find the log scale of data between 2 to 5.

array([   100.,   1000.,  10000., 100000.])

In [76]:
np.logspace([2],[3],axis=0)  #represent in 2d data.

array([[ 100.        ],
       [ 104.81131342],
       [ 109.8541142 ],
       [ 115.13953993],
       [ 120.67926406],
       [ 126.48552169],
       [ 132.57113656],
       [ 138.94954944],
       [ 145.63484775],
       [ 152.64179672],
       [ 159.98587196],
       [ 167.68329368],
       [ 175.75106249],
       [ 184.20699693],
       [ 193.06977289],
       [ 202.35896477],
       [ 212.09508879],
       [ 222.29964825],
       [ 232.99518105],
       [ 244.20530945],
       [ 255.95479227],
       [ 268.26957953],
       [ 281.1768698 ],
       [ 294.70517026],
       [ 308.88435965],
       [ 323.74575428],
       [ 339.32217719],
       [ 355.64803062],
       [ 372.75937203],
       [ 390.69399371],
       [ 409.49150624],
       [ 429.19342601],
       [ 449.8432669 ],
       [ 471.48663635],
       [ 494.17133613],
       [ 517.94746792],
       [ 542.86754393],
       [ 568.9866029 ],
       [ 596.36233166],
       [ 625.05519253],
       [ 655.12855686],
       [ 686.648

### Important Part

In [77]:
d=np.linspace(2,8,50)

In [78]:
d

array([2.        , 2.12244898, 2.24489796, 2.36734694, 2.48979592,
       2.6122449 , 2.73469388, 2.85714286, 2.97959184, 3.10204082,
       3.2244898 , 3.34693878, 3.46938776, 3.59183673, 3.71428571,
       3.83673469, 3.95918367, 4.08163265, 4.20408163, 4.32653061,
       4.44897959, 4.57142857, 4.69387755, 4.81632653, 4.93877551,
       5.06122449, 5.18367347, 5.30612245, 5.42857143, 5.55102041,
       5.67346939, 5.79591837, 5.91836735, 6.04081633, 6.16326531,
       6.28571429, 6.40816327, 6.53061224, 6.65306122, 6.7755102 ,
       6.89795918, 7.02040816, 7.14285714, 7.26530612, 7.3877551 ,
       7.51020408, 7.63265306, 7.75510204, 7.87755102, 8.        ])

In [79]:
d.ndim

1

In [80]:
d.shape


(50,)

In [81]:
d.reshape(50,1)  #reshaping the above data in 2d.

array([[2.        ],
       [2.12244898],
       [2.24489796],
       [2.36734694],
       [2.48979592],
       [2.6122449 ],
       [2.73469388],
       [2.85714286],
       [2.97959184],
       [3.10204082],
       [3.2244898 ],
       [3.34693878],
       [3.46938776],
       [3.59183673],
       [3.71428571],
       [3.83673469],
       [3.95918367],
       [4.08163265],
       [4.20408163],
       [4.32653061],
       [4.44897959],
       [4.57142857],
       [4.69387755],
       [4.81632653],
       [4.93877551],
       [5.06122449],
       [5.18367347],
       [5.30612245],
       [5.42857143],
       [5.55102041],
       [5.67346939],
       [5.79591837],
       [5.91836735],
       [6.04081633],
       [6.16326531],
       [6.28571429],
       [6.40816327],
       [6.53061224],
       [6.65306122],
       [6.7755102 ],
       [6.89795918],
       [7.02040816],
       [7.14285714],
       [7.26530612],
       [7.3877551 ],
       [7.51020408],
       [7.63265306],
       [7.755

In [82]:
#reshape is very important in DL and Computer Vision when we ll be playing with Imaage data.
d.reshape(1,2,25)  #3d 

array([[[2.        , 2.12244898, 2.24489796, 2.36734694, 2.48979592,
         2.6122449 , 2.73469388, 2.85714286, 2.97959184, 3.10204082,
         3.2244898 , 3.34693878, 3.46938776, 3.59183673, 3.71428571,
         3.83673469, 3.95918367, 4.08163265, 4.20408163, 4.32653061,
         4.44897959, 4.57142857, 4.69387755, 4.81632653, 4.93877551],
        [5.06122449, 5.18367347, 5.30612245, 5.42857143, 5.55102041,
         5.67346939, 5.79591837, 5.91836735, 6.04081633, 6.16326531,
         6.28571429, 6.40816327, 6.53061224, 6.65306122, 6.7755102 ,
         6.89795918, 7.02040816, 7.14285714, 7.26530612, 7.3877551 ,
         7.51020408, 7.63265306, 7.75510204, 7.87755102, 8.        ]]])

In [83]:
d.reshape(1,1,2,25) #4d

array([[[[2.        , 2.12244898, 2.24489796, 2.36734694, 2.48979592,
          2.6122449 , 2.73469388, 2.85714286, 2.97959184, 3.10204082,
          3.2244898 , 3.34693878, 3.46938776, 3.59183673, 3.71428571,
          3.83673469, 3.95918367, 4.08163265, 4.20408163, 4.32653061,
          4.44897959, 4.57142857, 4.69387755, 4.81632653, 4.93877551],
         [5.06122449, 5.18367347, 5.30612245, 5.42857143, 5.55102041,
          5.67346939, 5.79591837, 5.91836735, 6.04081633, 6.16326531,
          6.28571429, 6.40816327, 6.53061224, 6.65306122, 6.7755102 ,
          6.89795918, 7.02040816, 7.14285714, 7.26530612, 7.3877551 ,
          7.51020408, 7.63265306, 7.75510204, 7.87755102, 8.        ]]]])

In [84]:
np.random.rand(3) 
#the random data generated by rand function ll be in Guassian/Uniform Distribution/Normal Distribution between 0 to 1.

array([0.74393271, 0.2512476 , 0.72589846])

In [85]:
np.random.rand(50)

array([0.83902549, 0.43279147, 0.67337182, 0.36517848, 0.08183098,
       0.83429772, 0.13675853, 0.48858252, 0.67458797, 0.12250656,
       0.49966015, 0.30872569, 0.35556772, 0.52134796, 0.38525107,
       0.0429886 , 0.91113092, 0.79196044, 0.71767494, 0.31745807,
       0.81632114, 0.74074068, 0.57244702, 0.37149588, 0.98490202,
       0.39894568, 0.76247172, 0.90316308, 0.74176942, 0.33660372,
       0.09091297, 0.55841122, 0.94678072, 0.08971353, 0.11466322,
       0.220246  , 0.14325137, 0.68931944, 0.81560861, 0.51773207,
       0.18057548, 0.20880699, 0.04768604, 0.40914489, 0.21204501,
       0.4020493 , 0.72115199, 0.46725216, 0.92911269, 0.12812466])

In [86]:
np.random.randn(5)
#Return a sample (or samples) from the "standard normal" distribution.

array([-2.34706461, -1.40325792, -0.09603371, -0.99217578, -2.17576842])

In [87]:
#standard Normal Distribution----> mean=0 and S.D=1
#Normal Distrinution-----> mean and S.D can be anything.

In [88]:
np.random.randn(4,5)

array([[-1.67653678,  1.56835865,  1.26899172,  0.47940352,  0.20514825],
       [ 0.29930462,  0.3485193 ,  0.64838607,  0.27275478, -2.03773101],
       [-0.29412533,  0.03571055, -1.31145933, -1.99564859,  0.11630783],
       [ 0.66832159, -0.34296266,  0.15090219, -0.42195451, -1.00473651]])

In [89]:
np.random.randn(2,2,2)

array([[[ 0.21498364,  0.09622535],
        [-0.38104335,  0.17801866]],

       [[ 1.68652891,  0.70562103],
        [-1.48427214,  0.10453897]]])

In [90]:
np.random.randint(2,200) #return anyt random innteger value between 2 to 200,

16

In [91]:
np.random.randint(2,200,(4,4)) #generate a matrix of 4*4 between 2 to 200.

array([[ 33,  49,  16,  53],
       [175,  29,  29, 156],
       [193, 134,  85, 104],
       [ 90,   2,  29, 144]])

In [92]:
arr=np.random.randint(2,100,(4,4)) 

In [93]:
"""
Each time when we execute our np.random.rand values get different every time.
so we use seed method, to generate a random data but it will be constant every time.
the random value is determined by a parameter inside the seed function.
The random value will only chnage if the parameter of np.random.seed is changed otherwise it will stays the same
"""
np.random.seed(30)
np.random.rand(2,5)

array([[0.64414354, 0.38074849, 0.66304791, 0.16365073, 0.96260781],
       [0.34666184, 0.99175099, 0.2350579 , 0.58569427, 0.4066901 ]])

In [94]:
arr

array([[39, 88, 15, 10],
       [19, 14,  9, 47],
       [20, 37, 78, 24],
       [52, 72, 10, 23]])

In [95]:
arr.reshape(8,2)

array([[39, 88],
       [15, 10],
       [19, 14],
       [ 9, 47],
       [20, 37],
       [78, 24],
       [52, 72],
       [10, 23]])

In [96]:
arr.reshape(1,8,2)

array([[[39, 88],
        [15, 10],
        [19, 14],
        [ 9, 47],
        [20, 37],
        [78, 24],
        [52, 72],
        [10, 23]]])

In [97]:
arr.reshape(1,16)

array([[39, 88, 15, 10, 19, 14,  9, 47, 20, 37, 78, 24, 52, 72, 10, 23]])

In [98]:
#if you give a parameter ie:4,8,16 etc. the reshape then it will automatically detect-
#-the another parameter if we use any negative value(-1,-2,-23423525252,-23425456456 etc).
arr.reshape(4,-12348728437284)

array([[39, 88, 15, 10],
       [19, 14,  9, 47],
       [20, 37, 78, 24],
       [52, 72, 10, 23]])

In [99]:
#eg.we gave only 4 and didn't specify the 2nd paraameter and use it as -1, then it will auto. generate the data.
arr.reshape(4,-1) 

array([[39, 88, 15, 10],
       [19, 14,  9, 47],
       [20, 37, 78, 24],
       [52, 72, 10, 23]])

In [100]:
arr.reshape(16,-1)

array([[39],
       [88],
       [15],
       [10],
       [19],
       [14],
       [ 9],
       [47],
       [20],
       [37],
       [78],
       [24],
       [52],
       [72],
       [10],
       [23]])

In [101]:
arr.reshape(8,-1)

array([[39, 88],
       [15, 10],
       [19, 14],
       [ 9, 47],
       [20, 37],
       [78, 24],
       [52, 72],
       [10, 23]])

In [102]:
arr.max()

88

In [103]:
arr.min()

9

In [104]:
arr=np.random.randint(2,5,(5,5))

In [105]:
arr

array([[4, 4, 2, 2, 4],
       [2, 2, 4, 4, 4],
       [3, 2, 4, 2, 3],
       [4, 3, 2, 3, 4],
       [4, 3, 2, 3, 2]])

In [106]:
arr[2:,2:]  #slicing and extracting of data 

array([[4, 2, 3],
       [2, 3, 4],
       [2, 3, 2]])

In [107]:
arr[1:4,1:4]

array([[2, 4, 4],
       [2, 4, 2],
       [3, 2, 3]])

In [108]:
arr[:,[1,4]]

array([[4, 4],
       [2, 4],
       [2, 3],
       [3, 4],
       [3, 2]])

In [109]:
arr[:,[0,1,2]] #extracting all rows and only extraction 0th,1th,2nd column.

array([[4, 4, 2],
       [2, 2, 4],
       [3, 2, 4],
       [4, 3, 2],
       [4, 3, 2]])

In [110]:
arr>2

array([[ True,  True, False, False,  True],
       [False, False,  True,  True,  True],
       [ True, False,  True, False,  True],
       [ True,  True, False,  True,  True],
       [ True,  True, False,  True, False]])

In [111]:
arr[arr>2]

array([4, 4, 4, 4, 4, 4, 3, 4, 3, 4, 3, 3, 4, 4, 3, 3])

In [112]:
arr

array([[4, 4, 2, 2, 4],
       [2, 2, 4, 4, 4],
       [3, 2, 4, 2, 3],
       [4, 3, 2, 3, 4],
       [4, 3, 2, 3, 2]])

In [113]:
arr*arr #index wise (element wise) multiplication
#Its not a matrix multipllication.

array([[16, 16,  4,  4, 16],
       [ 4,  4, 16, 16, 16],
       [ 9,  4, 16,  4,  9],
       [16,  9,  4,  9, 16],
       [16,  9,  4,  9,  4]])

In [114]:
#This is a matrix multiplication.
arr@arr

array([[54, 46, 44, 46, 54],
       [56, 44, 44, 44, 52],
       [48, 39, 40, 37, 46],
       [56, 47, 42, 45, 54],
       [48, 41, 38, 39, 50]])

In [115]:
arr/0

C:\Users\asus\AppData\Local\Temp\ipykernel_1836\4291252909.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [116]:
arr**2

array([[16, 16,  4,  4, 16],
       [ 4,  4, 16, 16, 16],
       [ 9,  4, 16,  4,  9],
       [16,  9,  4,  9, 16],
       [16,  9,  4,  9,  4]], dtype=int32)

####  Broadcasting

In [117]:
arr1= np.zeros((3,4))

In [118]:
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [119]:
arr2=np.array([1,2,3,4])

In [120]:
arr1+arr2

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [121]:
arr1=arr1.reshape(4,-1)
arr1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [122]:
arr3=arr2.reshape(4,-1)

In [123]:
arr3

array([[1],
       [2],
       [3],
       [4]])

In [124]:
arr1+arr3

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.]])

In [125]:
arr1=np.zeros((3,4))

In [126]:
arr2=np.array([1,2,3])

In [127]:
arr3=arr2.reshape(3,-1)

In [128]:
arr3

array([[1],
       [2],
       [3]])

In [129]:
arr=arr1+arr3

In [130]:
arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [131]:
#Transpose 
arr.T 

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [132]:
arr=np.random.randint(2,10,(4,4))

In [133]:
arr

array([[7, 5, 3, 9],
       [3, 3, 2, 9],
       [9, 6, 8, 2],
       [3, 8, 2, 9]])

In [134]:
np.sqrt(arr)  #finding the square root od arr.

array([[2.64575131, 2.23606798, 1.73205081, 3.        ],
       [1.73205081, 1.73205081, 1.41421356, 3.        ],
       [3.        , 2.44948974, 2.82842712, 1.41421356],
       [1.73205081, 2.82842712, 1.41421356, 3.        ]])

In [135]:
np.exp(arr)

array([[1.09663316e+03, 1.48413159e+02, 2.00855369e+01, 8.10308393e+03],
       [2.00855369e+01, 2.00855369e+01, 7.38905610e+00, 8.10308393e+03],
       [8.10308393e+03, 4.03428793e+02, 2.98095799e+03, 7.38905610e+00],
       [2.00855369e+01, 2.98095799e+03, 7.38905610e+00, 8.10308393e+03]])

In [136]:
np.log10(arr)

array([[0.84509804, 0.69897   , 0.47712125, 0.95424251],
       [0.47712125, 0.47712125, 0.30103   , 0.95424251],
       [0.95424251, 0.77815125, 0.90308999, 0.30103   ],
       [0.47712125, 0.90308999, 0.30103   , 0.95424251]])